# Generated by Django 4.1.7 on 2023-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(default='jashd', upload_to='pics'),
            preserve_default=False,
        ),
    ]
